name: Build mockportal

env:
  dotnet_version: 6.0.x
  project_name: "MockPortal_ClientSide/MockPortal_ClientSide.csproj"

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: ListFolderContents
      run: ls -la /home/runner/work/mockportal/mockportal/MockPortal_ClientSide/bin/Release/net6.0/wwwroot/_framework
    - name: Test
      run: dotnet test -c Release --no-restore
    - name: Push _framework folder
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT_GITHUB_TOKEN }}
      with:
        source_folder: '/home/runner/work/mockportal/mockportal/MockPortal_ClientSide/bin/Release/net6.0/wwwroot/_framework'
        destination_repo: 'QED-DeveloperPortal/qed-developer-portal'
        destination_folder: '_framework'
        user_email: 'andrew@sitestudio.co'
        user_name: 'sitestudio'
        commit_msg: '[GHA] Update mockportal _framework files.'
      
