name: Build mockportal

env:
  dotnet_version: 7.0.x
  project_name: "MockPortal_ClientSide/MockPortal_ClientSide.csproj"

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    if: "contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnet_version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build and publish
      run: |
        dotnet build /home/runner/work/mockportal/mockportal/MockPortal_ClientSide/MockPortal_ClientSide.csproj -c Release
        dotnet publish /home/runner/work/mockportal/mockportal/MockPortal_ClientSide/MockPortal_ClientSide.csproj -c Release -o ./publish -f net7.0
        git config http.postBuffer 524288000
        git config --show-origin --get-all http.postBuffer
    - name: ListFolderContents
      run: ls -laR /home/runner/work/mockportal/mockportal/publish
    - name: Push publish folder
      uses: crykn/copy_folder_to_another_repo_action@v1.0.6
      env:
        API_TOKEN_GITHUB: ${{ secrets.PAT_GITHUB_TOKEN }}
      with:
        source_folder: '/home/runner/work/mockportal/mockportal/publish/wwwroot/mocks'
        destination_repo: 'QED-DeveloperPortal/qed-developer-portal'
        destination_branch: 'dev'
        destination_folder: 'mocks'
        user_email: 'andrew@sitestudio.co'
        user_name: 'sitestudio'
        commit_msg: '[GHA] Update mockportal files.'
        
